#!/bin/bash


findandinclude() {
	local DIRS=$(find . -maxdepth 1 -type d -regex '\./[0-9].*' | sort)
#	echo $1

	local DIR
	for DIR in $DIRS; do
		pushd $DIR > /dev/null
		echo $(pwd)
		findandinclude .
		popd +0 > /dev/null
	done

#	find . -type f -name '*.tex' -not -path '*/sav/*' | sort | xargs cat >> #1/\jobname.tmp
}

pushd $1 > /dev/null
findandinclude
popd +0 > /dev/null
